name = "EasyHybrid"
uuid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
authors = ["Lazaro Alonso", "Bernhard Ahrens", "Markus Reichstein"]
version = "0.1.1"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
ComponentArrays = "b0b7db55-cfe3-40fc-9ded-d10e2dbeff66"
DataFrameMacros = "75880514-38bc-4a95-a458-c2aea5a3a702"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
OptimizationOptimisers = "42dfb2eb-d2b4-4451-abcd-913932933ac1"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[extensions]
EasyHybridMakie = "Makie"

[compat]
AxisKeys = "0.2"
CSV = "0.10.15"
Chain = "0.6, 1"
ChainRulesCore = "1.25.1"
ComponentArrays = "0.15.28"
DataFrameMacros = "0.4"
DataFrames = "1"
Downloads = "1.6.0"
Flux = "0.16"
ForwardDiff = "1.0.1"
Hyperopt = "0.5.6"
JLD2 = "0.5.13, 0.6"
Lux = "1.12.4"
LuxCore = "1.2.4"
MLJ = "0.20"
MLUtils = "0.4.8"
Makie = "0.22, 0.23, 0.24"
NCDatasets = "0.14.8"
Optimisers = "0.4.6"
OptimizationOptimisers = "0.3.7"
Printf = "1.10, 1.11.0"
ProgressMeter = "1.10.4"
Reexport = "1.2.2"
Statistics = "1.10, 1.11.1"
StyledStrings = "1.0.3, 1.11.0"
Zygote = "0.7.7"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
