name = "EasyHybrid"
uuid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
authors = ["MR"]
version = "0.1.0"

[deps]
AxisKeys = "94b1ba4f-4ee9-5380-92f1-94cde586c3c5"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
DataFrameMacros = "75880514-38bc-4a95-a458-c2aea5a3a702"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCore = "bb33d45b-7691-41d6-9220-0943567d0623"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
NaNStatistics = "b946abbf-3ea7-4610-9019-9858bfdeaf2d"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
ChainRulesCore = "1.25.1"
ForwardDiff = "1.0.1"
Lux = "1.12.4"
LuxCore = "1.2.4"
MLJ = "0.20"
MLUtils = "0.4.8"
NaNStatistics = "0.6.51"
Optimisers = "0.4.6"
ProgressMeter = "1.10.4"
Statistics = "1.10, 1.11.1"
Zygote = "0.7.7"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
