[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Chain = "8be319e6-bccf-4806-a6f7-6fae938471bc"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
EasyHybrid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"
Hyperopt = "93e5fe13-2215-51db-baaf-2e9a34fb2712"

[sources]
EasyHybrid = {path = ".."}
