[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterVitepress = "4710194d-e776-4893-9690-8d956a29c365"
EasyHybrid = "61bb816a-e6af-4913-ab9e-91bff2e122e3"

[sources]
EasyHybrid = { path = ".." }